// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    /// <summary>
    /// Connection for LmaxWebSocket
    /// </summary>
    public sealed partial class ConnectSessionLmaxWebSocketMsg
    {
        public const ushort BlockLength = (ushort)52;
        public const ushort TemplateId = (ushort)8;
        public const ushort SchemaId = (ushort)3;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";

        private readonly ConnectSessionLmaxWebSocketMsg _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public ConnectSessionLmaxWebSocketMsg()
        {
            _parentMessage = this;
        }

        public void WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
        }

        public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset,  MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public void WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int SessionIdId = 1;
    public const int SessionIdSinceVersion = 0;
    public const int SessionIdDeprecated = 0;
    public bool SessionIdInActingVersion()
    {
        return _actingVersion >= SessionIdSinceVersion;
    }

        public const int SessionIdOffset = 0;

        public static string SessionIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SessionIdNullValue = (ushort)65535;
        public const ushort SessionIdMinValue = (ushort)0;
        public const ushort SessionIdMaxValue = (ushort)65534;

        public ushort SessionId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 0, value);
            }
        }


        public const int DataFeedHostId = 2;
    public const int DataFeedHostSinceVersion = 0;
    public const int DataFeedHostDeprecated = 0;
    public bool DataFeedHostInActingVersion()
    {
        return _actingVersion >= DataFeedHostSinceVersion;
    }

        public const int DataFeedHostOffset = 2;

        public static string DataFeedHostMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const byte DataFeedHostNullValue = (byte)0;
        public const byte DataFeedHostMinValue = (byte)32;
        public const byte DataFeedHostMaxValue = (byte)126;

        public const int DataFeedHostLength = 50;

        public byte GetDataFeedHost(int index)
        {
            if ((uint) index >= 50)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            return _buffer.CharGet(_offset + 2 + (index * 1));
        }

        public void SetDataFeedHost(int index, byte value)
        {
            if ((uint) index >= 50)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            _buffer.CharPut(_offset + 2 + (index * 1), value);
        }

        public ReadOnlySpan<byte> DataFeedHost
        {
            get => _buffer.AsReadOnlySpan<byte>(_offset + 2, DataFeedHostLength);
            set => value.CopyTo(_buffer.AsSpan<byte>(_offset + 2, DataFeedHostLength));
        }

        public Span<byte> DataFeedHostAsSpan()
        {
            return _buffer.AsSpan<byte>(_offset + 2, DataFeedHostLength);
        }

        public const string DataFeedHostCharacterEncoding = "ASCII";
        public static Encoding DataFeedHostResolvedCharacterEncoding = Encoding.GetEncoding(DataFeedHostCharacterEncoding);


        public int GetDataFeedHost(byte[] dst, int dstOffset)
        {
            const int length = 50;
            return GetDataFeedHost(new Span<byte>(dst, dstOffset, length));
        }

        public int GetDataFeedHost(Span<byte> dst)
        {
            const int length = 50;
            if (dst.Length < length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooSmall(dst.Length);
            }

            _buffer.GetBytes(_offset + 2, dst);
            return length;
        }

        public void SetDataFeedHost(byte[] src, int srcOffset)
        {
            SetDataFeedHost(new ReadOnlySpan<byte>(src, srcOffset, src.Length - srcOffset));
        }

        public void SetDataFeedHost(ReadOnlySpan<byte> src)
        {
            const int length = 50;
            if (src.Length > length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooLarge(src.Length);
            }

            _buffer.SetBytes(_offset + 2, src);
        }

        public void SetDataFeedHost(string value)
        {
            _buffer.SetNullTerminatedBytesFromString(DataFeedHostResolvedCharacterEncoding, value, _offset + 2, DataFeedHostLength, DataFeedHostNullValue);
        }
        public string GetDataFeedHost()
        {
            return _buffer.GetStringFromNullTerminatedBytes(DataFeedHostResolvedCharacterEncoding, _offset + 2, DataFeedHostLength, DataFeedHostNullValue);
        }

        public override string ToString()
        {
            var sb = new StringBuilder(100);
            this.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[ConnectSessionLmaxWebSocketMsg](sbeTemplateId=");
            builder.Append(ConnectSessionLmaxWebSocketMsg.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(ConnectSessionLmaxWebSocketMsg.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != ConnectSessionLmaxWebSocketMsg.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(ConnectSessionLmaxWebSocketMsg.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != ConnectSessionLmaxWebSocketMsg.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(ConnectSessionLmaxWebSocketMsg.BlockLength);
            builder.Append("):");

            builder.Append("SessionId=");
            builder.Append(this.SessionId);
            builder.Append('|');
            builder.Append("DataFeedHost=");
            for (int i = 0; i < DataFeedHostLength && this.GetDataFeedHost(i) > 0; ++i)
            {
                builder.Append((char)this.GetDataFeedHost(i));
            }

            this.Limit = originalLimit;

        }
    }
}
