// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    /// <summary>
    /// Connection for MT4
    /// </summary>
    public sealed partial class ConnectSessionMT4Msg
    {
        public const ushort BlockLength = (ushort)80;
        public const ushort TemplateId = (ushort)5;
        public const ushort SchemaId = (ushort)3;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";

        private readonly ConnectSessionMT4Msg _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public ConnectSessionMT4Msg()
        {
            _parentMessage = this;
        }

        public void WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
        }

        public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset,  MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public void WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int SessionIdId = 1;
    public const int SessionIdSinceVersion = 0;
    public const int SessionIdDeprecated = 0;
    public bool SessionIdInActingVersion()
    {
        return _actingVersion >= SessionIdSinceVersion;
    }

        public const int SessionIdOffset = 0;

        public static string SessionIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SessionIdNullValue = (ushort)65535;
        public const ushort SessionIdMinValue = (ushort)0;
        public const ushort SessionIdMaxValue = (ushort)65534;

        public ushort SessionId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 0, value);
            }
        }


        public const int LoginId = 2;
    public const int LoginSinceVersion = 0;
    public const int LoginDeprecated = 0;
    public bool LoginInActingVersion()
    {
        return _actingVersion >= LoginSinceVersion;
    }

        public const int LoginOffset = 2;

        public static string LoginMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const int LoginNullValue = -2147483648;
        public const int LoginMinValue = -2147483647;
        public const int LoginMaxValue = 2147483647;

        public int Login
        {
            get
            {
                return _buffer.Int32GetLittleEndian(_offset + 2);
            }
            set
            {
                _buffer.Int32PutLittleEndian(_offset + 2, value);
            }
        }


        public const int PasswordId = 3;
    public const int PasswordSinceVersion = 0;
    public const int PasswordDeprecated = 0;
    public bool PasswordInActingVersion()
    {
        return _actingVersion >= PasswordSinceVersion;
    }

        public const int PasswordOffset = 6;

        public static string PasswordMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const byte PasswordNullValue = (byte)0;
        public const byte PasswordMinValue = (byte)32;
        public const byte PasswordMaxValue = (byte)126;

        public const int PasswordLength = 20;

        public byte GetPassword(int index)
        {
            if ((uint) index >= 20)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            return _buffer.CharGet(_offset + 6 + (index * 1));
        }

        public void SetPassword(int index, byte value)
        {
            if ((uint) index >= 20)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            _buffer.CharPut(_offset + 6 + (index * 1), value);
        }

        public ReadOnlySpan<byte> Password
        {
            get => _buffer.AsReadOnlySpan<byte>(_offset + 6, PasswordLength);
            set => value.CopyTo(_buffer.AsSpan<byte>(_offset + 6, PasswordLength));
        }

        public Span<byte> PasswordAsSpan()
        {
            return _buffer.AsSpan<byte>(_offset + 6, PasswordLength);
        }

        public const string PasswordCharacterEncoding = "ASCII";
        public static Encoding PasswordResolvedCharacterEncoding = Encoding.GetEncoding(PasswordCharacterEncoding);


        public int GetPassword(byte[] dst, int dstOffset)
        {
            const int length = 20;
            return GetPassword(new Span<byte>(dst, dstOffset, length));
        }

        public int GetPassword(Span<byte> dst)
        {
            const int length = 20;
            if (dst.Length < length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooSmall(dst.Length);
            }

            _buffer.GetBytes(_offset + 6, dst);
            return length;
        }

        public void SetPassword(byte[] src, int srcOffset)
        {
            SetPassword(new ReadOnlySpan<byte>(src, srcOffset, src.Length - srcOffset));
        }

        public void SetPassword(ReadOnlySpan<byte> src)
        {
            const int length = 20;
            if (src.Length > length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooLarge(src.Length);
            }

            _buffer.SetBytes(_offset + 6, src);
        }

        public void SetPassword(string value)
        {
            _buffer.SetNullTerminatedBytesFromString(PasswordResolvedCharacterEncoding, value, _offset + 6, PasswordLength, PasswordNullValue);
        }
        public string GetPassword()
        {
            return _buffer.GetStringFromNullTerminatedBytes(PasswordResolvedCharacterEncoding, _offset + 6, PasswordLength, PasswordNullValue);
        }

        public const int HostId = 4;
    public const int HostSinceVersion = 0;
    public const int HostDeprecated = 0;
    public bool HostInActingVersion()
    {
        return _actingVersion >= HostSinceVersion;
    }

        public const int HostOffset = 26;

        public static string HostMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const byte HostNullValue = (byte)0;
        public const byte HostMinValue = (byte)32;
        public const byte HostMaxValue = (byte)126;

        public const int HostLength = 50;

        public byte GetHost(int index)
        {
            if ((uint) index >= 50)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            return _buffer.CharGet(_offset + 26 + (index * 1));
        }

        public void SetHost(int index, byte value)
        {
            if ((uint) index >= 50)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            _buffer.CharPut(_offset + 26 + (index * 1), value);
        }

        public ReadOnlySpan<byte> Host
        {
            get => _buffer.AsReadOnlySpan<byte>(_offset + 26, HostLength);
            set => value.CopyTo(_buffer.AsSpan<byte>(_offset + 26, HostLength));
        }

        public Span<byte> HostAsSpan()
        {
            return _buffer.AsSpan<byte>(_offset + 26, HostLength);
        }

        public const string HostCharacterEncoding = "ASCII";
        public static Encoding HostResolvedCharacterEncoding = Encoding.GetEncoding(HostCharacterEncoding);


        public int GetHost(byte[] dst, int dstOffset)
        {
            const int length = 50;
            return GetHost(new Span<byte>(dst, dstOffset, length));
        }

        public int GetHost(Span<byte> dst)
        {
            const int length = 50;
            if (dst.Length < length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooSmall(dst.Length);
            }

            _buffer.GetBytes(_offset + 26, dst);
            return length;
        }

        public void SetHost(byte[] src, int srcOffset)
        {
            SetHost(new ReadOnlySpan<byte>(src, srcOffset, src.Length - srcOffset));
        }

        public void SetHost(ReadOnlySpan<byte> src)
        {
            const int length = 50;
            if (src.Length > length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooLarge(src.Length);
            }

            _buffer.SetBytes(_offset + 26, src);
        }

        public void SetHost(string value)
        {
            _buffer.SetNullTerminatedBytesFromString(HostResolvedCharacterEncoding, value, _offset + 26, HostLength, HostNullValue);
        }
        public string GetHost()
        {
            return _buffer.GetStringFromNullTerminatedBytes(HostResolvedCharacterEncoding, _offset + 26, HostLength, HostNullValue);
        }

        public const int PortId = 5;
    public const int PortSinceVersion = 0;
    public const int PortDeprecated = 0;
    public bool PortInActingVersion()
    {
        return _actingVersion >= PortSinceVersion;
    }

        public const int PortOffset = 76;

        public static string PortMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const int PortNullValue = -2147483648;
        public const int PortMinValue = -2147483647;
        public const int PortMaxValue = 2147483647;

        public int Port
        {
            get
            {
                return _buffer.Int32GetLittleEndian(_offset + 76);
            }
            set
            {
                _buffer.Int32PutLittleEndian(_offset + 76, value);
            }
        }


        public override string ToString()
        {
            var sb = new StringBuilder(100);
            this.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[ConnectSessionMT4Msg](sbeTemplateId=");
            builder.Append(ConnectSessionMT4Msg.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(ConnectSessionMT4Msg.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != ConnectSessionMT4Msg.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(ConnectSessionMT4Msg.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != ConnectSessionMT4Msg.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(ConnectSessionMT4Msg.BlockLength);
            builder.Append("):");

            builder.Append("SessionId=");
            builder.Append(this.SessionId);
            builder.Append('|');
            builder.Append("Login=");
            builder.Append(this.Login);
            builder.Append('|');
            builder.Append("Password=");
            for (int i = 0; i < PasswordLength && this.GetPassword(i) > 0; ++i)
            {
                builder.Append((char)this.GetPassword(i));
            }
            builder.Append('|');
            builder.Append("Host=");
            for (int i = 0; i < HostLength && this.GetHost(i) > 0; ++i)
            {
                builder.Append((char)this.GetHost(i));
            }
            builder.Append('|');
            builder.Append("Port=");
            builder.Append(this.Port);

            this.Limit = originalLimit;

        }
    }
}
