// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum FXBoxEngine : byte
    {
        SESSION = 0,
        MDE = 1,
        TDE = 2,
        ALGO = 3,
        JOURNAL = 4,
        AGENT = 5,
        AGENT_HUB = 6,
        NULL_VALUE = 255
    }
}
