// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum MarketDataSubscriptionLevel : byte
    {
        LEVEL_1 = 0,
        LEVEL_2 = 1,
        NULL_VALUE = 255
    }
}
