// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    /// <summary>
    /// Send new trade order server respone.
    /// </summary>
    public sealed partial class NewOrderResponseMsg
    {
        public const ushort BlockLength = (ushort)54;
        public const ushort TemplateId = (ushort)3;
        public const ushort SchemaId = (ushort)2;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";

        private readonly NewOrderResponseMsg _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public NewOrderResponseMsg()
        {
            _parentMessage = this;
        }

        public void WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
        }

        public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset,  MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public void WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int SessionIdId = 1;
    public const int SessionIdSinceVersion = 0;
    public const int SessionIdDeprecated = 0;
    public bool SessionIdInActingVersion()
    {
        return _actingVersion >= SessionIdSinceVersion;
    }

        public const int SessionIdOffset = 0;

        public static string SessionIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SessionIdNullValue = (ushort)65535;
        public const ushort SessionIdMinValue = (ushort)0;
        public const ushort SessionIdMaxValue = (ushort)65534;

        public ushort SessionId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 0, value);
            }
        }


        public const int SymbolIdId = 2;
    public const int SymbolIdSinceVersion = 0;
    public const int SymbolIdDeprecated = 0;
    public bool SymbolIdInActingVersion()
    {
        return _actingVersion >= SymbolIdSinceVersion;
    }

        public const int SymbolIdOffset = 2;

        public static string SymbolIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SymbolIdNullValue = (ushort)65535;
        public const ushort SymbolIdMinValue = (ushort)0;
        public const ushort SymbolIdMaxValue = (ushort)65534;

        public ushort SymbolId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 2);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 2, value);
            }
        }


        public const int TradeIdId = 3;
    public const int TradeIdSinceVersion = 0;
    public const int TradeIdDeprecated = 0;
    public bool TradeIdInActingVersion()
    {
        return _actingVersion >= TradeIdSinceVersion;
    }

        public const int TradeIdOffset = 4;

        public static string TradeIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort TradeIdNullValue = (ushort)65535;
        public const ushort TradeIdMinValue = (ushort)0;
        public const ushort TradeIdMaxValue = (ushort)65534;

        public ushort TradeId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 4);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 4, value);
            }
        }


        public const int OrderDirectionTypeId = 4;
    public const int OrderDirectionTypeSinceVersion = 0;
    public const int OrderDirectionTypeDeprecated = 0;
    public bool OrderDirectionTypeInActingVersion()
    {
        return _actingVersion >= OrderDirectionTypeSinceVersion;
    }

        public const int OrderDirectionTypeOffset = 6;

        public static string OrderDirectionTypeMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public OrderDirectionType OrderDirectionType
        {
            get
            {
                return (OrderDirectionType)_buffer.Uint8Get(_offset + 6);
            }
            set
            {
                _buffer.Uint8Put(_offset + 6, (byte)value);
            }
        }


        public const int OrderExecutionTypeId = 5;
    public const int OrderExecutionTypeSinceVersion = 0;
    public const int OrderExecutionTypeDeprecated = 0;
    public bool OrderExecutionTypeInActingVersion()
    {
        return _actingVersion >= OrderExecutionTypeSinceVersion;
    }

        public const int OrderExecutionTypeOffset = 7;

        public static string OrderExecutionTypeMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public OrderExecutionType OrderExecutionType
        {
            get
            {
                return (OrderExecutionType)_buffer.Uint8Get(_offset + 7);
            }
            set
            {
                _buffer.Uint8Put(_offset + 7, (byte)value);
            }
        }


        public const int OrderFillTypeId = 6;
    public const int OrderFillTypeSinceVersion = 0;
    public const int OrderFillTypeDeprecated = 0;
    public bool OrderFillTypeInActingVersion()
    {
        return _actingVersion >= OrderFillTypeSinceVersion;
    }

        public const int OrderFillTypeOffset = 8;

        public static string OrderFillTypeMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public OrderFillType OrderFillType
        {
            get
            {
                return (OrderFillType)_buffer.Uint8Get(_offset + 8);
            }
            set
            {
                _buffer.Uint8Put(_offset + 8, (byte)value);
            }
        }


        public const int OrderRequestPriceId = 7;
    public const int OrderRequestPriceSinceVersion = 0;
    public const int OrderRequestPriceDeprecated = 0;
    public bool OrderRequestPriceInActingVersion()
    {
        return _actingVersion >= OrderRequestPriceSinceVersion;
    }

        public const int OrderRequestPriceOffset = 9;

        public static string OrderRequestPriceMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const float OrderRequestPriceNullValue = float.NaN;
        public const float OrderRequestPriceMinValue = 1.401298464324817E-45f;
        public const float OrderRequestPriceMaxValue = 3.4028234663852886E38f;

        public float OrderRequestPrice
        {
            get
            {
                return _buffer.FloatGetLittleEndian(_offset + 9);
            }
            set
            {
                _buffer.FloatPutLittleEndian(_offset + 9, value);
            }
        }


        public const int OrderFillPriceId = 8;
    public const int OrderFillPriceSinceVersion = 0;
    public const int OrderFillPriceDeprecated = 0;
    public bool OrderFillPriceInActingVersion()
    {
        return _actingVersion >= OrderFillPriceSinceVersion;
    }

        public const int OrderFillPriceOffset = 13;

        public static string OrderFillPriceMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const float OrderFillPriceNullValue = float.NaN;
        public const float OrderFillPriceMinValue = 1.401298464324817E-45f;
        public const float OrderFillPriceMaxValue = 3.4028234663852886E38f;

        public float OrderFillPrice
        {
            get
            {
                return _buffer.FloatGetLittleEndian(_offset + 13);
            }
            set
            {
                _buffer.FloatPutLittleEndian(_offset + 13, value);
            }
        }


        public const int OrderStopLossPriceId = 9;
    public const int OrderStopLossPriceSinceVersion = 0;
    public const int OrderStopLossPriceDeprecated = 0;
    public bool OrderStopLossPriceInActingVersion()
    {
        return _actingVersion >= OrderStopLossPriceSinceVersion;
    }

        public const int OrderStopLossPriceOffset = 17;

        public static string OrderStopLossPriceMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const float OrderStopLossPriceNullValue = float.NaN;
        public const float OrderStopLossPriceMinValue = 1.401298464324817E-45f;
        public const float OrderStopLossPriceMaxValue = 3.4028234663852886E38f;

        public float OrderStopLossPrice
        {
            get
            {
                return _buffer.FloatGetLittleEndian(_offset + 17);
            }
            set
            {
                _buffer.FloatPutLittleEndian(_offset + 17, value);
            }
        }


        public const int OrderTakeProfitPriceId = 10;
    public const int OrderTakeProfitPriceSinceVersion = 0;
    public const int OrderTakeProfitPriceDeprecated = 0;
    public bool OrderTakeProfitPriceInActingVersion()
    {
        return _actingVersion >= OrderTakeProfitPriceSinceVersion;
    }

        public const int OrderTakeProfitPriceOffset = 21;

        public static string OrderTakeProfitPriceMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const float OrderTakeProfitPriceNullValue = float.NaN;
        public const float OrderTakeProfitPriceMinValue = 1.401298464324817E-45f;
        public const float OrderTakeProfitPriceMaxValue = 3.4028234663852886E38f;

        public float OrderTakeProfitPrice
        {
            get
            {
                return _buffer.FloatGetLittleEndian(_offset + 21);
            }
            set
            {
                _buffer.FloatPutLittleEndian(_offset + 21, value);
            }
        }


        public const int OrderQuantityId = 11;
    public const int OrderQuantitySinceVersion = 0;
    public const int OrderQuantityDeprecated = 0;
    public bool OrderQuantityInActingVersion()
    {
        return _actingVersion >= OrderQuantitySinceVersion;
    }

        public const int OrderQuantityOffset = 25;

        public static string OrderQuantityMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const float OrderQuantityNullValue = float.NaN;
        public const float OrderQuantityMinValue = 1.401298464324817E-45f;
        public const float OrderQuantityMaxValue = 3.4028234663852886E38f;

        public float OrderQuantity
        {
            get
            {
                return _buffer.FloatGetLittleEndian(_offset + 25);
            }
            set
            {
                _buffer.FloatPutLittleEndian(_offset + 25, value);
            }
        }


        public const int OrderProcessingResultId = 12;
    public const int OrderProcessingResultSinceVersion = 0;
    public const int OrderProcessingResultDeprecated = 0;
    public bool OrderProcessingResultInActingVersion()
    {
        return _actingVersion >= OrderProcessingResultSinceVersion;
    }

        public const int OrderProcessingResultOffset = 29;

        public static string OrderProcessingResultMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public OrderProcessingResult OrderProcessingResult
        {
            get
            {
                return (OrderProcessingResult)_buffer.Uint8Get(_offset + 29);
            }
            set
            {
                _buffer.Uint8Put(_offset + 29, (byte)value);
            }
        }


        public const int TimestampQuoteId = 13;
    public const int TimestampQuoteSinceVersion = 0;
    public const int TimestampQuoteDeprecated = 0;
    public bool TimestampQuoteInActingVersion()
    {
        return _actingVersion >= TimestampQuoteSinceVersion;
    }

        public const int TimestampQuoteOffset = 30;

        public static string TimestampQuoteMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const long TimestampQuoteNullValue = -9223372036854775808L;
        public const long TimestampQuoteMinValue = -9223372036854775807L;
        public const long TimestampQuoteMaxValue = 9223372036854775807L;

        public long TimestampQuote
        {
            get
            {
                return _buffer.Int64GetLittleEndian(_offset + 30);
            }
            set
            {
                _buffer.Int64PutLittleEndian(_offset + 30, value);
            }
        }


        public const int TimestampTradeSendId = 14;
    public const int TimestampTradeSendSinceVersion = 0;
    public const int TimestampTradeSendDeprecated = 0;
    public bool TimestampTradeSendInActingVersion()
    {
        return _actingVersion >= TimestampTradeSendSinceVersion;
    }

        public const int TimestampTradeSendOffset = 38;

        public static string TimestampTradeSendMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const long TimestampTradeSendNullValue = -9223372036854775808L;
        public const long TimestampTradeSendMinValue = -9223372036854775807L;
        public const long TimestampTradeSendMaxValue = 9223372036854775807L;

        public long TimestampTradeSend
        {
            get
            {
                return _buffer.Int64GetLittleEndian(_offset + 38);
            }
            set
            {
                _buffer.Int64PutLittleEndian(_offset + 38, value);
            }
        }


        public const int TimestampTradeResponseId = 15;
    public const int TimestampTradeResponseSinceVersion = 0;
    public const int TimestampTradeResponseDeprecated = 0;
    public bool TimestampTradeResponseInActingVersion()
    {
        return _actingVersion >= TimestampTradeResponseSinceVersion;
    }

        public const int TimestampTradeResponseOffset = 46;

        public static string TimestampTradeResponseMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const long TimestampTradeResponseNullValue = -9223372036854775808L;
        public const long TimestampTradeResponseMinValue = -9223372036854775807L;
        public const long TimestampTradeResponseMaxValue = 9223372036854775807L;

        public long TimestampTradeResponse
        {
            get
            {
                return _buffer.Int64GetLittleEndian(_offset + 46);
            }
            set
            {
                _buffer.Int64PutLittleEndian(_offset + 46, value);
            }
        }


        public override string ToString()
        {
            var sb = new StringBuilder(100);
            this.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[NewOrderResponseMsg](sbeTemplateId=");
            builder.Append(NewOrderResponseMsg.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(NewOrderResponseMsg.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != NewOrderResponseMsg.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(NewOrderResponseMsg.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != NewOrderResponseMsg.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(NewOrderResponseMsg.BlockLength);
            builder.Append("):");

            builder.Append("SessionId=");
            builder.Append(this.SessionId);
            builder.Append('|');
            builder.Append("SymbolId=");
            builder.Append(this.SymbolId);
            builder.Append('|');
            builder.Append("TradeId=");
            builder.Append(this.TradeId);
            builder.Append('|');
            builder.Append("OrderDirectionType=");
            builder.Append(this.OrderDirectionType);
            builder.Append('|');
            builder.Append("OrderExecutionType=");
            builder.Append(this.OrderExecutionType);
            builder.Append('|');
            builder.Append("OrderFillType=");
            builder.Append(this.OrderFillType);
            builder.Append('|');
            builder.Append("OrderRequestPrice=");
            builder.Append(this.OrderRequestPrice);
            builder.Append('|');
            builder.Append("OrderFillPrice=");
            builder.Append(this.OrderFillPrice);
            builder.Append('|');
            builder.Append("OrderStopLossPrice=");
            builder.Append(this.OrderStopLossPrice);
            builder.Append('|');
            builder.Append("OrderTakeProfitPrice=");
            builder.Append(this.OrderTakeProfitPrice);
            builder.Append('|');
            builder.Append("OrderQuantity=");
            builder.Append(this.OrderQuantity);
            builder.Append('|');
            builder.Append("OrderProcessingResult=");
            builder.Append(this.OrderProcessingResult);
            builder.Append('|');
            builder.Append("TimestampQuote=");
            builder.Append(this.TimestampQuote);
            builder.Append('|');
            builder.Append("TimestampTradeSend=");
            builder.Append(this.TimestampTradeSend);
            builder.Append('|');
            builder.Append("TimestampTradeResponse=");
            builder.Append(this.TimestampTradeResponse);

            this.Limit = originalLimit;

        }
    }
}
