// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum OrderFillType : byte
    {
        /// <summary>
        /// Good Till Cancel.
        /// </summary>
        GTC = 1,
        /// <summary>
        /// At the Opening.
        /// </summary>
        OPG = 2,
        /// <summary>
        /// Immediate or Cancel.
        /// </summary>
        IOC = 3,
        /// <summary>
        /// Fill or Kill.
        /// </summary>
        FOK = 4,
        NULL_VALUE = 255
    }
}
