// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum OrderCloseReason : byte
    {
        /// <summary>
        /// Order closed on take profit hit.
        /// </summary>
        TP_HIT = 1,
        /// <summary>
        /// Order closed on stop loss hit.
        /// </summary>
        SL_HIT = 2,
        /// <summary>
        /// Order closed manually on request.
        /// </summary>
        ON_REQUEST = 3,
        NULL_VALUE = 255
    }
}
