// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum OrderDirectionType : byte
    {
        /// <summary>
        /// Buy the security.
        /// </summary>
        BUY = 1,
        /// <summary>
        /// Sell the security.
        /// </summary>
        SELL = 2,
        NULL_VALUE = 255
    }
}
