// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum RithmicServerType : byte
    {
        RITHMIC01 = 0,
        RITHMIC_DEMO = 1,
        RITHMIC_GERMANY = 2,
        RITHMIC_DEMO_SINGAPORE = 3,
        RITHMIC_DEMO_HONK_KONG = 4,
        RITHMIC_DEMO_CHICAGO_AREA = 5,
        RITHMIC_DEMO_CHICAGO_AREA2 = 6,
        NULL_VALUE = 255
    }
}
