// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    /// <summary>
    /// Connection for SaxoBankApi
    /// </summary>
    public sealed partial class SaxoBankApiMsg
    {
        public const ushort BlockLength = (ushort)102;
        public const ushort TemplateId = (ushort)12;
        public const ushort SchemaId = (ushort)3;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";

        private readonly SaxoBankApiMsg _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public SaxoBankApiMsg()
        {
            _parentMessage = this;
        }

        public void WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
        }

        public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset,  MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public void WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int SessionIdId = 1;
    public const int SessionIdSinceVersion = 0;
    public const int SessionIdDeprecated = 0;
    public bool SessionIdInActingVersion()
    {
        return _actingVersion >= SessionIdSinceVersion;
    }

        public const int SessionIdOffset = 0;

        public static string SessionIdMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SessionIdNullValue = (ushort)65535;
        public const ushort SessionIdMinValue = (ushort)0;
        public const ushort SessionIdMaxValue = (ushort)65534;

        public ushort SessionId
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 0, value);
            }
        }


        public const int SessionTokenId = 2;
    public const int SessionTokenSinceVersion = 0;
    public const int SessionTokenDeprecated = 0;
    public bool SessionTokenInActingVersion()
    {
        return _actingVersion >= SessionTokenSinceVersion;
    }

        public const int SessionTokenOffset = 2;

        public static string SessionTokenMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const byte SessionTokenNullValue = (byte)0;
        public const byte SessionTokenMinValue = (byte)32;
        public const byte SessionTokenMaxValue = (byte)126;

        public const int SessionTokenLength = 100;

        public byte GetSessionToken(int index)
        {
            if ((uint) index >= 100)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            return _buffer.CharGet(_offset + 2 + (index * 1));
        }

        public void SetSessionToken(int index, byte value)
        {
            if ((uint) index >= 100)
            {
                ThrowHelper.ThrowIndexOutOfRangeException(index);
            }

            _buffer.CharPut(_offset + 2 + (index * 1), value);
        }

        public ReadOnlySpan<byte> SessionToken
        {
            get => _buffer.AsReadOnlySpan<byte>(_offset + 2, SessionTokenLength);
            set => value.CopyTo(_buffer.AsSpan<byte>(_offset + 2, SessionTokenLength));
        }

        public Span<byte> SessionTokenAsSpan()
        {
            return _buffer.AsSpan<byte>(_offset + 2, SessionTokenLength);
        }

        public const string SessionTokenCharacterEncoding = "ASCII";
        public static Encoding SessionTokenResolvedCharacterEncoding = Encoding.GetEncoding(SessionTokenCharacterEncoding);


        public int GetSessionToken(byte[] dst, int dstOffset)
        {
            const int length = 100;
            return GetSessionToken(new Span<byte>(dst, dstOffset, length));
        }

        public int GetSessionToken(Span<byte> dst)
        {
            const int length = 100;
            if (dst.Length < length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooSmall(dst.Length);
            }

            _buffer.GetBytes(_offset + 2, dst);
            return length;
        }

        public void SetSessionToken(byte[] src, int srcOffset)
        {
            SetSessionToken(new ReadOnlySpan<byte>(src, srcOffset, src.Length - srcOffset));
        }

        public void SetSessionToken(ReadOnlySpan<byte> src)
        {
            const int length = 100;
            if (src.Length > length)
            {
                ThrowHelper.ThrowWhenSpanLengthTooLarge(src.Length);
            }

            _buffer.SetBytes(_offset + 2, src);
        }

        public void SetSessionToken(string value)
        {
            _buffer.SetNullTerminatedBytesFromString(SessionTokenResolvedCharacterEncoding, value, _offset + 2, SessionTokenLength, SessionTokenNullValue);
        }
        public string GetSessionToken()
        {
            return _buffer.GetStringFromNullTerminatedBytes(SessionTokenResolvedCharacterEncoding, _offset + 2, SessionTokenLength, SessionTokenNullValue);
        }

        public override string ToString()
        {
            var sb = new StringBuilder(100);
            this.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[SaxoBankApiMsg](sbeTemplateId=");
            builder.Append(SaxoBankApiMsg.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(SaxoBankApiMsg.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != SaxoBankApiMsg.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(SaxoBankApiMsg.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != SaxoBankApiMsg.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(SaxoBankApiMsg.BlockLength);
            builder.Append("):");

            builder.Append("SessionId=");
            builder.Append(this.SessionId);
            builder.Append('|');
            builder.Append("SessionToken=");
            for (int i = 0; i < SessionTokenLength && this.GetSessionToken(i) > 0; ++i)
            {
                builder.Append((char)this.GetSessionToken(i));
            }

            this.Limit = originalLimit;

        }
    }
}
