// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum ServerSessionRegisterStatus : byte
    {
        REGISTERED = 0,
        NULL_VALUE = 255
    }
}
