// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum SessionConnectStatus : byte
    {
        CONNECTED = 0,
        DISCONNECTED = 1,
        TIME_OUT = 2,
        WRONG_CREDENTIALS = 3,
        ALREADY_CONNECTED = 4,
        NULL_VALUE = 255
    }
}
