// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    /// <summary>
    /// Test the Cloud Gateway connections.
    /// </summary>
    public sealed partial class StartMeasuringHealthCheckReport
    {
        public const ushort BlockLength = (ushort)2;
        public const ushort TemplateId = (ushort)4;
        public const ushort SchemaId = (ushort)6;
        public const ushort SchemaVersion = (ushort)0;
        public const string SemanticType = "";

        private readonly StartMeasuringHealthCheckReport _parentMessage;
        private DirectBuffer _buffer;
        private int _offset;
        private int _limit;
        private int _actingBlockLength;
        private int _actingVersion;

        public int Offset { get { return _offset; } }

        public StartMeasuringHealthCheckReport()
        {
            _parentMessage = this;
        }

        public void WrapForEncode(DirectBuffer buffer, int offset)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = BlockLength;
            _actingVersion = SchemaVersion;
            Limit = offset + _actingBlockLength;
        }

        public void WrapForEncodeAndApplyHeader(DirectBuffer buffer, int offset,  MessageHeader headerEncoder)
        {
            headerEncoder.Wrap(buffer, offset, SchemaVersion);
            headerEncoder.BlockLength = BlockLength;
            headerEncoder.TemplateId = TemplateId;
            headerEncoder.SchemaId = SchemaId;
            headerEncoder.Version = SchemaVersion;
            
            WrapForEncode(buffer, offset + MessageHeader.Size);
        }

        public void WrapForDecode(DirectBuffer buffer, int offset, int actingBlockLength, int actingVersion)
        {
            _buffer = buffer;
            _offset = offset;
            _actingBlockLength = actingBlockLength;
            _actingVersion = actingVersion;
            Limit = offset + _actingBlockLength;
        }

        public int Size
        {
            get
            {
                return _limit - _offset;
            }
        }

        public int Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _buffer.CheckLimit(value);
                _limit = value;
            }
        }


        public const int SequenceNumberId = 1;
    public const int SequenceNumberSinceVersion = 0;
    public const int SequenceNumberDeprecated = 0;
    public bool SequenceNumberInActingVersion()
    {
        return _actingVersion >= SequenceNumberSinceVersion;
    }

        public const int SequenceNumberOffset = 0;

        public static string SequenceNumberMetaAttribute(MetaAttribute metaAttribute)
        {
            switch (metaAttribute)
            {
                case MetaAttribute.Epoch: return "";
                case MetaAttribute.TimeUnit: return "";
                case MetaAttribute.SemanticType: return "";
                case MetaAttribute.Presence: return "required";
            }

            return "";
        }

        public const ushort SequenceNumberNullValue = (ushort)65535;
        public const ushort SequenceNumberMinValue = (ushort)0;
        public const ushort SequenceNumberMaxValue = (ushort)65534;

        public ushort SequenceNumber
        {
            get
            {
                return _buffer.Uint16GetLittleEndian(_offset + 0);
            }
            set
            {
                _buffer.Uint16PutLittleEndian(_offset + 0, value);
            }
        }


        public override string ToString()
        {
            var sb = new StringBuilder(100);
            this.BuildString(sb);
            return sb.ToString();
        }

        internal void BuildString(StringBuilder builder)
        {
            if (_buffer == null)
            {
                throw new ArgumentNullException("_buffer");
            }

            int originalLimit = this.Limit;
            this.Limit = _offset + _actingBlockLength;
            builder.Append("[StartMeasuringHealthCheckReport](sbeTemplateId=");
            builder.Append(StartMeasuringHealthCheckReport.TemplateId);
            builder.Append("|sbeSchemaId=");
            builder.Append(StartMeasuringHealthCheckReport.SchemaId);
            builder.Append("|sbeSchemaVersion=");
            if (_parentMessage._actingVersion != StartMeasuringHealthCheckReport.SchemaVersion)
            {
                builder.Append(_parentMessage._actingVersion);
                builder.Append('/');
            }
            builder.Append(StartMeasuringHealthCheckReport.SchemaVersion);
            builder.Append("|sbeBlockLength=");
            if (_actingBlockLength != StartMeasuringHealthCheckReport.BlockLength)
            {
                builder.Append(_actingBlockLength);
                builder.Append('/');
            }
            builder.Append(StartMeasuringHealthCheckReport.BlockLength);
            builder.Append("):");

            builder.Append("SequenceNumber=");
            builder.Append(this.SequenceNumber);

            this.Limit = originalLimit;

        }
    }
}
