// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum StreamServer : byte
    {
        SESSION_SERVER = 0,
        MDE_SERVER = 1,
        TDE_SERVER = 2,
        ALGO_SERVER = 3,
        JOURNAL_SERVER = 4,
        AGENT_HUB_SERVER = 5,
        NULL_VALUE = 255
    }
}
