// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum StreamClient : byte
    {
        SESSION_CLIENT = 0,
        MDE_CLIENT = 1,
        TDE_CLIENT = 2,
        ALGO_CLIENT = 3,
        JOURNAL_CLIENT = 4,
        AGENT_HUB_CLIENT = 5,
        NULL_VALUE = 255
    }
}
