// <auto-generated>
//     Generated SBE (Simple Binary Encoding) message codec
// </auto-generated>

#pragma warning disable 1591 // disable warning on missing comments
using System;
using System.Text;
using Org.SbeTool.Sbe.Dll;

namespace MsgSchema
{
    public enum SubscribeMDStatus : byte
    {
        SUBSCRIBED = 0,
        UNSUBSCRIBED = 1,
        REJECTED = 2,
        ALREADY_SUBSCRIBED = 3,
        NULL_VALUE = 255
    }
}
